### ISSUE TITLE
Object #<Namespace> has no method 'socket'

### ISSUE THREAD

**Issue by dokithonon** [mheap/socketio-chat-example#5]
Hello Michael,
I ran your code exactly has it is and I get the error : Object #<Namespace> has no method 'socket'
in app.js at line 33 :       io.sockets.socket(clients[data.username].socket).emit("add-message", data);

Can you help ?
Thanks a lot

**Comment by gs-akhan** [comment]
Hi.. I will look into this..

**Comment by mheap** [comment]
Thanks @gs-akhan :)

I imagine that the issue is that the code is for Socket.io < 1.0 - I was hoping to find time to take a look, but @gs-akhan has offered to fix it

**Comment by gs-akhan** [comment]
@mheap  Your welcome ..
So here is the fix.. I have bumped socket.io version in package.json to "*" . I tested it and it works too
please have a look before I send a pull.. thanks.. :)
https://github.com/gs-akhan/socketio-chat-example/commit/7439fbd27b6b4e202227b76a814101ef8cadec6d

**Comment by gs-akhan** [comment]
opps sorry I accidentaly removed that console.. will add it back too ;)

**Comment by gs-akhan** [comment]
I think we are good to go here. :+1:

**Comment by dokithonon** [comment]
Thanks a lot !

On Thu, Jun 19, 2014 at 2:36 PM, gs-akhan notifications@github.com wrote:

> I think we are good to go here. [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mheap/socketio-chat-example/issues/5#issuecomment-46554667
> .

## 

Thomas Doki-Thonon
+33678619100
dokithonon@gmail.com

**Comment by mheap** [comment]
@gs-akhan Looks good to me, but can we pin the version at >= 1.0.0? The new code won't work with 0.9

**Comment by gs-akhan** [comment]
Sure.. I shall add that as well

**Comment by gs-akhan** [comment]
@mheap Hi,
Here we go ..https://github.com/mheap/socketio-chat-example/pull/4
Thanks
